"""freebies table update

Revision ID: 2575c5a52ba4
Revises: 04a72e01b799
Create Date: 2025-05-26 07:50:42.496011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2575c5a52ba4'
down_revision = '04a72e01b799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
