"""Create freebies table

Revision ID: 6497d9e2ba3c
Revises: d9ff836c1875
Create Date: 2025-05-26 07:37:58.753840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6497d9e2ba3c'
down_revision = 'd9ff836c1875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
